# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'views/mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1190, 605)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mainWindow.sizePolicy().hasHeightForWidth())
        mainWindow.setSizePolicy(sizePolicy)
        mainWindow.setMinimumSize(QtCore.QSize(788, 605))
        mainWindow.setAcceptDrops(True)
        mainWindow.setAutoFillBackground(False)
        mainWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setAcceptDrops(True)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.buildMode = QtWidgets.QToolButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.buildMode.setFont(font)
        self.buildMode.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.buildMode.setCheckable(True)
        self.buildMode.setChecked(True)
        self.buildMode.setObjectName("buildMode")
        self.horizontalLayout_4.addWidget(self.buildMode)
        self.runMode = QtWidgets.QToolButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.runMode.setFont(font)
        self.runMode.setCheckable(True)
        self.runMode.setObjectName("runMode")
        self.horizontalLayout_4.addWidget(self.runMode)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.toolbox = QtWidgets.QVBoxLayout()
        self.toolbox.setContentsMargins(-1, -1, 0, -1)
        self.toolbox.setObjectName("toolbox")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(200, 70))
        self.groupBox.setMaximumSize(QtCore.QSize(175, 70))
        self.groupBox.setObjectName("groupBox")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 20, 200, 41))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.wireMode = QtWidgets.QToolButton(self.gridLayoutWidget_2)
        self.wireMode.setMinimumSize(QtCore.QSize(66, 25))
        self.wireMode.setAutoFillBackground(False)
        self.wireMode.setCheckable(True)
        self.wireMode.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.wireMode.setObjectName("wireMode")
        self.gridLayout.addWidget(self.wireMode, 0, 1, 1, 1)
        self.selectMode = QtWidgets.QToolButton(self.gridLayoutWidget_2)
        self.selectMode.setMinimumSize(QtCore.QSize(66, 25))
        self.selectMode.setAutoFillBackground(False)
        self.selectMode.setCheckable(True)
        self.selectMode.setChecked(True)
        self.selectMode.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.selectMode.setObjectName("selectMode")
        self.gridLayout.addWidget(self.selectMode, 0, 0, 1, 1)
        self.deleteMode = QtWidgets.QToolButton(self.gridLayoutWidget_2)
        self.deleteMode.setMinimumSize(QtCore.QSize(66, 25))
        self.deleteMode.setAutoFillBackground(False)
        self.deleteMode.setCheckable(True)
        self.deleteMode.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.deleteMode.setObjectName("deleteMode")
        self.gridLayout.addWidget(self.deleteMode, 0, 2, 1, 1)
        self.toolbox.addWidget(self.groupBox)
        spacerItem2 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.toolbox.addItem(spacerItem2)
        self.toolboxComponents = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolboxComponents.sizePolicy().hasHeightForWidth())
        self.toolboxComponents.setSizePolicy(sizePolicy)
        self.toolboxComponents.setMinimumSize(QtCore.QSize(200, 400))
        self.toolboxComponents.setMaximumSize(QtCore.QSize(175, 1000))
        self.toolboxComponents.setObjectName("toolboxComponents")
        self.gridLayoutWidget = QtWidgets.QWidget(self.toolboxComponents)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 20, 201, 381))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.toolboxComponentsGrid = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.toolboxComponentsGrid.setObjectName("toolboxComponentsGrid")
        self.newBattery = DraggableComponentButton(self.gridLayoutWidget)
        self.newBattery.setMinimumSize(QtCore.QSize(80, 80))
        self.newBattery.setAutoFillBackground(False)
        self.newBattery.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.newBattery.setObjectName("newBattery")
        self.toolboxComponentsGrid.addWidget(self.newBattery, 1, 0, 1, 1)
        self.newBulb = DraggableComponentButton(self.gridLayoutWidget)
        self.newBulb.setMinimumSize(QtCore.QSize(80, 80))
        self.newBulb.setAutoFillBackground(False)
        self.newBulb.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.newBulb.setObjectName("newBulb")
        self.toolboxComponentsGrid.addWidget(self.newBulb, 1, 1, 1, 1)
        self.newResistor = DraggableComponentButton(self.gridLayoutWidget)
        self.newResistor.setMinimumSize(QtCore.QSize(80, 80))
        self.newResistor.setAutoFillBackground(False)
        self.newResistor.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.newResistor.setObjectName("newResistor")
        self.toolboxComponentsGrid.addWidget(self.newResistor, 2, 0, 1, 1)
        self.newSwitch = DraggableComponentButton(self.gridLayoutWidget)
        self.newSwitch.setMinimumSize(QtCore.QSize(80, 80))
        self.newSwitch.setAutoFillBackground(False)
        self.newSwitch.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.newSwitch.setObjectName("newSwitch")
        self.toolboxComponentsGrid.addWidget(self.newSwitch, 2, 1, 1, 1)
        self.newButton = DraggableComponentButton(self.gridLayoutWidget)
        self.newButton.setMinimumSize(QtCore.QSize(80, 80))
        self.newButton.setAutoFillBackground(False)
        self.newButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.newButton.setObjectName("newButton")
        self.toolboxComponentsGrid.addWidget(self.newButton, 3, 0, 1, 1)
        self.newVoltmeter = DraggableComponentButton(self.gridLayoutWidget)
        self.newVoltmeter.setMinimumSize(QtCore.QSize(80, 80))
        self.newVoltmeter.setAutoFillBackground(False)
        self.newVoltmeter.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.newVoltmeter.setObjectName("newVoltmeter")
        self.toolboxComponentsGrid.addWidget(self.newVoltmeter, 3, 1, 1, 1)
        self.newAmmeter = DraggableComponentButton(self.gridLayoutWidget)
        self.newAmmeter.setMinimumSize(QtCore.QSize(80, 80))
        self.newAmmeter.setAutoFillBackground(False)
        self.newAmmeter.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.newAmmeter.setObjectName("newAmmeter")
        self.toolboxComponentsGrid.addWidget(self.newAmmeter, 4, 0, 1, 1)
        self.toolbox.addWidget(self.toolboxComponents)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.toolbox.addItem(spacerItem3)
        self.horizontalLayout.addLayout(self.toolbox)
        self.circuitDiagram = CircuitDiagramView(self.centralwidget)
        self.circuitDiagram.setMinimumSize(QtCore.QSize(480, 480))
        self.circuitDiagram.setMouseTracking(True)
        self.circuitDiagram.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.circuitDiagram.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.circuitDiagram.setRenderHints(QtGui.QPainter.HighQualityAntialiasing|QtGui.QPainter.SmoothPixmapTransform)
        self.circuitDiagram.setResizeAnchor(QtWidgets.QGraphicsView.AnchorViewCenter)
        self.circuitDiagram.setViewportUpdateMode(QtWidgets.QGraphicsView.FullViewportUpdate)
        self.circuitDiagram.setObjectName("circuitDiagram")
        self.horizontalLayout.addWidget(self.circuitDiagram)
        self.properties = QtWidgets.QTabWidget(self.centralwidget)
        self.properties.setMinimumSize(QtCore.QSize(250, 0))
        self.properties.setMaximumSize(QtCore.QSize(250, 16777215))
        self.properties.setTabPosition(QtWidgets.QTabWidget.North)
        self.properties.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.properties.setElideMode(QtCore.Qt.ElideRight)
        self.properties.setMovable(False)
        self.properties.setObjectName("properties")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 253, 471))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout.setContentsMargins(-1, 10, -1, -1)
        self.formLayout.setObjectName("formLayout")
        self.componentTypeLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.componentTypeLabel.setFont(font)
        self.componentTypeLabel.setObjectName("componentTypeLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.componentTypeLabel)
        self.componentType = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.componentType.setEnabled(False)
        self.componentType.setMaximumSize(QtCore.QSize(100, 16777215))
        self.componentType.setObjectName("componentType")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.componentType)
        self.resistanceLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.resistanceLabel.setFont(font)
        self.resistanceLabel.setObjectName("resistanceLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.resistanceLabel)
        self.resistance = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.resistance.setEnabled(False)
        self.resistance.setMinimumSize(QtCore.QSize(95, 0))
        self.resistance.setMaximumSize(QtCore.QSize(95, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.resistance.setFont(font)
        self.resistance.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.resistance.setSpecialValueText("")
        self.resistance.setAccelerated(False)
        self.resistance.setProperty("showGroupSeparator", False)
        self.resistance.setDecimals(1)
        self.resistance.setMinimum(0.0)
        self.resistance.setSingleStep(0.1)
        self.resistance.setProperty("value", 1.0)
        self.resistance.setObjectName("resistance")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.resistance)
        self.voltageLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.voltageLabel.setFont(font)
        self.voltageLabel.setObjectName("voltageLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.voltageLabel)
        self.voltage = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.voltage.setEnabled(False)
        self.voltage.setMinimumSize(QtCore.QSize(95, 0))
        self.voltage.setMaximumSize(QtCore.QSize(95, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.voltage.setFont(font)
        self.voltage.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.voltage.setSpecialValueText("")
        self.voltage.setAccelerated(False)
        self.voltage.setProperty("showGroupSeparator", False)
        self.voltage.setDecimals(1)
        self.voltage.setMinimum(0.0)
        self.voltage.setProperty("value", 9.0)
        self.voltage.setObjectName("voltage")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.voltage)
        self.closedLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.closedLabel.setFont(font)
        self.closedLabel.setObjectName("closedLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.closedLabel)
        self.closed = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.closed.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.closed.setFont(font)
        self.closed.setText("")
        self.closed.setObjectName("closed")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.closed)
        self.currentLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.currentLabel.setFont(font)
        self.currentLabel.setObjectName("currentLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.currentLabel)
        self.current = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.current.setEnabled(False)
        self.current.setMinimumSize(QtCore.QSize(78, 0))
        self.current.setMaximumSize(QtCore.QSize(58, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.current.setFont(font)
        self.current.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.current.setObjectName("current")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.current)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.properties.addTab(self.tab, "")
        self.horizontalLayout.addWidget(self.properties)
        self.verticalLayout.addLayout(self.horizontalLayout)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1190, 22))
        self.menubar.setDefaultUp(False)
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuWindow = QtWidgets.QMenu(self.menubar)
        self.menuWindow.setObjectName("menuWindow")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        mainWindow.setMenuBar(self.menubar)
        self.statusBar = QtWidgets.QStatusBar(mainWindow)
        self.statusBar.setObjectName("statusBar")
        mainWindow.setStatusBar(self.statusBar)
        self.actionFile = QtWidgets.QAction(mainWindow)
        self.actionFile.setObjectName("actionFile")
        self.actionNew = QtWidgets.QAction(mainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(mainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(mainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionClose = QtWidgets.QAction(mainWindow)
        self.actionClose.setIconVisibleInMenu(True)
        self.actionClose.setObjectName("actionClose")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClose)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuWindow.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(mainWindow)
        self.properties.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "FlappyEagle"))
        self.buildMode.setText(_translate("mainWindow", "Build"))
        self.runMode.setText(_translate("mainWindow", "Run"))
        self.groupBox.setTitle(_translate("mainWindow", "Tools"))
        self.wireMode.setText(_translate("mainWindow", "Wire"))
        self.selectMode.setText(_translate("mainWindow", "Select"))
        self.deleteMode.setText(_translate("mainWindow", "Delete"))
        self.toolboxComponents.setTitle(_translate("mainWindow", "Components"))
        self.newBattery.setText(_translate("mainWindow", "Battery"))
        self.newBulb.setText(_translate("mainWindow", "Bulb"))
        self.newResistor.setText(_translate("mainWindow", "Resistor"))
        self.newSwitch.setText(_translate("mainWindow", "Switch"))
        self.newButton.setText(_translate("mainWindow", "Button"))
        self.newVoltmeter.setText(_translate("mainWindow", "Voltmeter"))
        self.newAmmeter.setText(_translate("mainWindow", "Ammeter"))
        self.componentTypeLabel.setText(_translate("mainWindow", "Component Type"))
        self.resistanceLabel.setText(_translate("mainWindow", "Resistance"))
        self.resistance.setSuffix(_translate("mainWindow", "Ω"))
        self.voltageLabel.setText(_translate("mainWindow", "Voltage"))
        self.voltage.setSuffix(_translate("mainWindow", "V"))
        self.closedLabel.setText(_translate("mainWindow", "Closed"))
        self.currentLabel.setText(_translate("mainWindow", "Current"))
        self.current.setText(_translate("mainWindow", "0.0A"))
        self.properties.setTabText(self.properties.indexOf(self.tab), _translate("mainWindow", "Properties"))
        self.menuFile.setTitle(_translate("mainWindow", "File"))
        self.menuEdit.setTitle(_translate("mainWindow", "Edit"))
        self.menuWindow.setTitle(_translate("mainWindow", "Window"))
        self.menuHelp.setTitle(_translate("mainWindow", "Help"))
        self.actionFile.setText(_translate("mainWindow", "File"))
        self.actionNew.setText(_translate("mainWindow", "New"))
        self.actionOpen.setText(_translate("mainWindow", "Open"))
        self.actionSave.setText(_translate("mainWindow", "Save"))
        self.actionClose.setText(_translate("mainWindow", "Close"))

from views.CircuitDiagramView import CircuitDiagramView
from views.DraggableComponentButton import DraggableComponentButton

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())

